---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.22.3
    app.quarkus.io/build-timestamp: 2025-05-24 - 23:02:12 +0000
  labels:
    app.kubernetes.io/name: quarkus-simple-service
    app.kubernetes.io/version: latest
    app.kubernetes.io/managed-by: quarkus
  name: quarkus-simple-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: quarkus-simple-service
    app.kubernetes.io/version: latest
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.22.3
    app.quarkus.io/build-timestamp: 2025-05-24 - 23:02:12 +0000
  labels:
    app.kubernetes.io/name: quarkus-simple-service
    app.kubernetes.io/version: latest
    app.kubernetes.io/managed-by: quarkus
  name: quarkus-simple-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: quarkus-simple-service
      app.kubernetes.io/version: latest
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.22.3
        app.quarkus.io/build-timestamp: 2025-05-24 - 23:02:12 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: quarkus-simple-service
        app.kubernetes.io/version: latest
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: adrianohenriquess/quarkus-simple-service:fault-simulator
          imagePullPolicy: Always
          name: quarkus-simple-service
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
